### PR TITLE
added short output format

### PR DESCRIPTION
**Pull request by kbaum**
Wanted to be able to pass a temporary oauth token to a script that expires.  See changes to README.

thx!

### CODE REVIEW

**Comment by pedro** [comment]
Hey!

Amazing idea and execution, really love these maybe unexpected use cases :}

I had a bit of trouble running this on 1.9 though, which is the ruby version the Heroku toolbelt ships with. Can you make this work on 1.9 too?

Thanks,

**Comment by kbaum** [comment]
Sure.  Will do.




Question for you.. what is the best way to test changes locally?  Currently, i am pushing to my git rep and re-installing the plugin each time. 




thx!

-karl

**Comment by pedro** [comment]
Ah! Such a good question :} Just clone this repo/your fork under `~/.heroku/plugins`.

This is where the `heroku` cli will load files, so any changes you make there are going to be effective immediately.

Needless to say we also need a better way of writing tests for these; if you're curious [this describes some changes we're envisioning for cli plugins](https://blog.heroku.com/archives/2015/3/19/making_cli_plugins_better_with_a_new_architecture).

**Comment by kbaum** [comment]
Ok.  Made compatible with ruby 1.9.

thx!

**Comment by pedro** [comment]
Looks great, thank you!

**Pull request merged**
